### ISSUE TITLE
Ability to change the QR radius

### ISSUE THREAD

**Issue by rohanrajpal** [phippsytech/svelte-qrious#1]
This is quite a simple & effective library to get QR codes working with Svelte, thanks a ton!

I was wondering if we could add an option to change the radius of the QR codes & make them something like below?

<img width="351" alt="image" src="https://user-images.githubusercontent.com/7023147/187025428-40c3884f-6d11-4e09-be15-cdc3e6eaf1cc.png">

I'm currently using the `qr-creator` library to achieve the same:

```svelte
<script lang="ts">
    import { browser } from '$app/env';

    export let url: string;
    let qrcode: HTMLElement | undefined = undefined;

    async function renderQrCode() {
        const QrCreator = (await import('qr-creator')).default;
        if (qrcode) {
            qrcode.firstChild?.remove();
            QrCreator.render(
                {
                    text: url,
                    radius: 0.5, // 0.0 to 0.5
                    ecLevel: 'L', // L, M, Q, H
                    fill: '#3C77F1',
                    background: null, // color or null for transparent
                    size: 240, // in pixels
                },
                qrcode,
            );
            qrcode.firstChild.style.margin = 'auto';
        }
    }

    $: if (url && browser) renderQrCode();
</script>

<div
    bind:this={qrcode}
    class="w-full h-[278px] mx-auto p-4 border-4 border-spur-blue-500 rounded-md"
/>
```

**Comment by michaelphipps** [comment]
I'm so sorry for the delay in responding.  This issue flew under my radar and I missed it.

Svelte QRious is just a wrapper around QRious.js.  The radius effect you are asking about is not a feature of that library,

**Comment by michaelphipps** [comment]
I'm so sorry for the delay in responding. This issue flew under my radar and I missed it.

Svelte QRious is just a wrapper around QRious.js. The radius effect you are asking about is not a feature of that library,
